## 🆘 Pedido de Suporte

📌 **Módulo/Conteúdo:** <nome do módulo ou conteúdo>  
🎥 **Nome da aula:** <nome da aula>  
📝 **Descrição:**  
<Detalhe ao máximo o seu problema, explique o que tentou fazer e o que não funcionou.>  

🖥️ **Evidências:**  
<Adicione prints, mensagens de erro, logs, trechos do código no Visual Studio Code, etc.>  

💻 **Código:**  
```javascript
// Adicione aqui o trecho de código que deu erro
